---
title: "Tutoriel DADA2"
output: github_document
Fait par: Toky Emmanuel Rabemanana Rahaga
---

```{r}

#Importation du package dada2 pour l'analyse des données de séquençage

library(dada2)
packageVersion("dada2")
```

```{r}

# Spécification du chemin du répertoire où se trouvent les fichiers fastq

path <- "/home/rstudio/Tutorieldada2update/MiSeq_SOP"

#verification si tout le repertoire est bien present

list.files(path)
```


```{r}

#Extraire les fichiers FASTQ de lecture avant (R1) dont le nom contient _R1_001.fastq" puis pareil avec R2

fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))

# Obtention des noms des échantillons en récupérant la première partie du nom de fichier, en les séparant par le caractère '_'

sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
```
```{r}

# Génération d'un graphique des profils de qualité pour les deux premiers fichiers R1

plotQualityProfile(fnFs[1:2])
```
```{r}

# Génération d'un graphique des profils de qualité pour les deux premiers fichiers R2

plotQualityProfile(fnRs[1:2])
```
```{r}
# Définition des chemins: des fichiers filtrés pour les premières lectures (R1) en les nommant avec "_F_filt.fastq.gz".

filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))

#Définition des chemins: des fichiers filtrés pour les secondes lectures (R2) en les nommant avec "_R_filt.fastq.gz"

filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))

#Attribution des noms d'échantillons aux fichiers filtrés R1 et R2 afin de faciliter le suivi.

names(filtFs) <- sample.names
names(filtRs) <- sample.names
```

```{r}

#->Filtrage et de nettoyage multiparamètres des séquences FASTQ pour plusieurs échantillons 

##-> la longueur de coupe : les séquences avant (fnFs) sont tronquées à 240 bases, tandis que les séquences arrière (fnRs) le sont à 160 bases. De plus, le seuil d'erreur maximal est fixé à maxEE=(2,2), ce qui signifie que les séquences avec plus de 2 erreurs cumulées seront éliminées. Si une séquence contient une base N, elle sera également rejetée (maxN=0). Les bases avec un score de qualité inférieur à 2 (truncQ=2) seront coupées ou supprimées. Les séquences de phix seront retirées (rm.phix=true), et les fichiers filtrés seront compressés au format gzip (compress=True). Enfin, la variable out stocke le résultat de la fonction filterAndTrim(), qui fournit un tableau avec des informations sur le nombre de séquences avant et après le filtrage

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE) # On Windows set multithread=FALSE
head(out)
```
```{r}
#Évaluer les erreurs dans les séquences avant à partir des fichiers filtrés

##->DADA2 développe un modèle d'erreur pour les séquences R1(Forward) afin de corriger les erreurs de séquençage. Pour ce faire, elle s'appuie sur les séquences filtrées (contenues dans filtFs) pour estimer les erreurs typiques de séquençage, telles que les substitutions, les insertions, etc. errF est l'objet qui contient le modèle d'erreur appris pour les séquences R1

errF <- learnErrors(filtFs, multithread=TRUE)
```
```{r}
## Meme principe que précedemment avec la séquence R2(Reverse)
errR <- learnErrors(filtRs, multithread=TRUE)
```
```{r}
#Représentation visuelle des taux d'erreur estimés des lectures R1

## création d'un graphique illustrant les erreurs de séquençage apprises dans les séquences avant (errF). Ce graphique permet de visualiser le taux d'erreur en fonction des scores de qualité (Phred) et d’évaluer la qualité globale de vos données de séquençage. Avec nominalQ=TRUE, cela signifie que les scores de qualité (Q-scores) sur l'axe des ordonnées du graphique seront présentés avec leurs valeurs nominales, c'est-à-dire en Phred

plotErrors(errF, nominalQ=TRUE)
```
```{r}
#Application du modèle d'erreur estimé aux lectures (R1)

##->utilisation de la fonction dada pour les séquences filtrées ainsi que le modèle d'erreur estimé, et pour appliquer une approche fondée sur le maximum de vraisemblance afin d'identifier les variantes de séquences précises, appelées ASVs (Amplicon Sequence Variants). Les résultats montrent que pour l'échantillon 1, nous avons 7113 lectures (fragments d'ADN séquencés après le filtrage), dont 1979 sont des séquences uniques

dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
```
```{r}
# idem que precedement mais cette fois-ci pour R2
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
```
```{r}

#Representation du processus DADA appliqué pour le premier échantillon

dadaFs[[1]]
```
```{r}

#Fusion des résultats des lectures R1 et R2 pour créer des séquences d'amplicon assemblées 

mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)

#Apperçu des premières séquences fusionnées pour le premier échantillon dans l'objet mergers

head(mergers[[1]])
```
```{r}
# Générer une table de séquences (ASV) à partir des séquences fusionnées

##->Colonne=ASV, et ligne=abondance dans chaque échantillon. Résumé complet des ASVs détectées et de leur abondance dans tes échantillons.

seqtab <- makeSequenceTable(mergers)

#Présentation des dimensions de la table de séquences

##->Total d'échantillons : 20 (représentés par des lignes).
##->Total d'ASVs identifiées dans chaque échantillon : 293 (représentées par des colonnes

dim(seqtab)
```
```{r}
# Détermination du nombre de séquences par longueur et affichage de la distribution

##->Fonction nchar() : Calcule la longueur de chaque ASV; fonction table() : Compte le nombre d'ASVs ayant une longueur spécifique.Interprétation des résultats : 88 ASVs ont une longueur de 252 bases.

table(nchar(getSequences(seqtab)))
```
```{r}
#Détection et suppression des séquences chimériques générées en utilisant une méthode de consensus

seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)

#Presentation des dimensions de la table de sequence après suppression des séquences chimériques
##->Résultats :Échantillons restants : 20, Chimères identifiées : 61, ASVs restantes : 232

dim(seqtab.nochim)
```
```{r}
# Calcul de la proportion de séquences non chimériques par rapport à la table de séquences initiales
##->Résultat: 96,4 % des séquences étaient non chimériques dans la table initiale et ont été conservées dans la table seqtab.nochim après la suppression des chimères

sum(seqtab.nochim)/sum(seqtab)
```
```{r}
#Extraction des séquences uniques [function()] et comptage [sum()]

getN <- function(x) sum(getUniques(x))

# Création de matrice de suivi avec les statistiques de chaque étape du traitement
##paramètres: out : Nombre de séquences après l'étape filterAndTrim(), sapply(dadaFs, getN) : Nombre de séquences uniques après dénucléotidation des lectures "forward", sapply(dadaRs, getN) : Nombre de séquences uniques après dénucléotidation des lectures "reverse, sapply(mergers, getN) : Nombre de séquences uniques après fusion des lectures avant et arrière, rowSums(seqtab.nochim) : Nombre total d'ASVs non chimériques après suppression des chimères

track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))

# Modificartion des noms des colonnes de la matrice "track", assignation et affichage

##But: inclure des descriptions appropriées
###->Table d'échantillons : Chaque ligne de la table correspond à un échantillon spécifique, vérification des données : La fonction sample.names.head(track) affiche les premières lignes de la table. Donc, Suivi des séquences : permet d'observer l'évolution des séquences à chaque étape du pipeline DADA2.

colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)
```
```{r}
#Assigner les données taxonomiques non chimériques à l'aide d'une base SILVA

##PS: préalablement telecharger le fichier Silva v132+verification s'il est bien installé

taxa <- assignTaxonomy(seqtab.nochim, "/home/rstudio/Tutorieldada2update/silva_nr_v132_train_set.fa.gz", multithread=TRUE)
```
```{r}
taxa <- addSpecies(taxa, "/home/rstudio/Tutorieldada2update/silva_species_assignment_v132.fa.gz")
```
```{r}
#Mise des résultats de taxonomie dans une nouvelle variable

taxa.print <- taxa 

#Retirer les noms de lignes[rowname()<-NULL] pour l'affichage [head] uniquement des taxonomies

rownames(taxa.print) <- NULL
head(taxa.print)
```
```{r}
#Appeler le package DECIPHER pour le traitement des séquences, autre alternative utilisation classifieur par des sifer

library(DECIPHER); packageVersion("DECIPHER")
```
```{r}
dna <- DNAStringSet(getSequences(seqtab.nochim)) # Create a DNAStringSet from the ASVs
load("/home/rstudio/Tutorieldada2update/SILVA_SSU_r138_2019.RData") 
ids <- IdTaxa(dna, trainingSet, strand="top", processors=NULL, verbose=FALSE) 
ranks <- c("domain", "phylum", "class", "order", "family", "genus", "species")
# Convertir l'objet de sortie de la classe 'Taxa' en une matrice analogue à celle produite par assignTaxonomy
taxid <- t(sapply(ids, function(x) {
        m <- match(ranks, x$rank)
        taxa <- x$taxon[m]
        taxa[startsWith(taxa, "unclassified_")] <- NA
        taxa
}))
colnames(taxid) <- ranks; rownames(taxid) <- getSequences(seqtab.nochim)
```
```{r}
#Evaluation de la precision
## Extraction des séquences uniques de l'échantillon "Mock"

unqs.mock <- seqtab.nochim["Mock",]

## Conserver uniquement les ASVs présentes dans MOK en les classant par ordre décroissant.
unqs.mock <- sort(unqs.mock[unqs.mock>0], decreasing=TRUE) 
cat("DADA2 inferred", length(unqs.mock), "sample sequences present in the Mock community.\n")
```

```{r}
#Vérification des Correspondances des ASVs avec les Séquences de Référence dans l'Échantillon Mock

##->Le fichier HMP_MOCK.v35.fasta est chargé et enregistré sous mock.ref. Pour chaque ASV identifiée dans l'échantillon Mock, il est vérifié si son nom figure dans les séquences de référence contenues dans mock.ref. Si c'est le cas, cette ASV est considérée comme une correspondance[cat("Of those")]. Un message affiche le nombre d'ASVs qui correspondent exactement aux séquences de référence.
mock.ref <- getSequences(file.path(path, "HMP_MOCK.v35.fasta"))
match.ref <- sum(sapply(names(unqs.mock), function(x) any(grepl(x, mock.ref))))
cat("Of those,", sum(match.ref), "were exact matches to the expected reference sequences.\n")
```


```{r}
#BONUS: Transfert à Phyloseq

#Chargement du package phyloseq

##Pour info: cette library sera utilisée pour organiser, analyser et visualiser les données de séquences après le traitement par DADA2. Une fois que les séquences d'amplification (ASVs) ont été générées et classifiées, phyloseq permet de manipuler ces données taxonomiques et écologiques (par exemple, calculer la diversité alpha/bêta, générer des graphiques comme des arbres phylogénétiques ou des heatmaps).

library(phyloseq); packageVersion("phyloseq")
```
```{r}
#Chargement du package Biostrings

##Pour info: Dans DADA2, Biostrings pourrait être utilisée pour extraire des séquences d'ADN uniques, les comparer, ou effectuer d'autres manipulations sur les séquences d'ASVs.

library(Biostrings); packageVersion("Biostrings")
```
```{r}
#Chargement du package ggplot2

##Pour info:Il est souvent utilisé pour visualiser les résultats après l'analyse DADA2. Il pourrait être utilisé pour produire des graphiques de qualité, comme des graphiques de distribution des ASVs, des courbes de diversité, ou encore pour visualiser des taux d'erreur et la qualité des séquences dans les étapes de filtrage.

library(ggplot2); packageVersion("ggplot2")
```
```{r}
#Application d'un thème noir et blanc par défaut aux graphiques ggplot2
theme_set(theme_bw())
```
```{r}
#Extraction des noms des échantillons à partir de la table des séquences non chimériques

samples.out <- rownames(seqtab.nochim)

#Extraction de la première partie des chaînes de caractères contenues dans samples.out, avant chaque occurrence de la lettre "D", et stocke cette partie dans l'objet subject

subject <- sapply(strsplit(samples.out, "D"), `[`, 1)

#Extraction du premier caractère de chaque élément dans la variable subject et implementer dans le vecteur gender

gender <- substr(subject,1,1)

#Extraction de l'identifiant du sujet en supprimant la première lettre

subject <- substr(subject,2,999)

#Exctraction la deuxième partie des chaînes de caractères de samples.out[sequence] (après la lettre "D") et la convertit en un nombre entier, qui est ensuite stocké dans l'objet day

day <- as.integer(sapply(strsplit(samples.out, "D"), `[`, 2))

#Création du dataframe samdf
##->Cette ligne crée un dataframe nommé samdf à partir de trois vecteurs : subject, gender, et day. Chaque vecteur représente une colonne du dataframe.

samdf <- data.frame(Subject=subject, Gender=gender, Day=day)

#Ajout d'une colonne When avec la valeur par défaut "Early"
##->Une nouvelle colonne When est ajoutée au dataframe, et tous les échantillons sont initialement étiquetés comme "Early". Cela signifie que, par défaut, tous les échantillons sont considérés comme ayant été prélevés tôt dans l'étude.

samdf$When <- "Early"

#Modification de la colonne When en fonction de la valeur de Day
##->Cette ligne modifie les valeurs dans la colonne When pour les échantillons où le nombre de jours (Day) est supérieur à 100. Pour ces échantillons, la valeur de When est changée de "Early" à "Late". Cela permet de catégoriser les échantillons selon qu'ils ont été prélevés tôt ou tard dans l'étude.

samdf$When[samdf$Day>100] <- "Late"

#Définition des noms de ligne du dataframe samdf
##->Cette ligne attribue des noms de ligne au dataframe samdf en utilisant le vecteur samples.out. Cela permet de rendre le dataframe plus facile à interpréter et à manipuler en associant chaque ligne à un nom d'échantillon spécifique.

rownames(samdf) <- samples.out
```
```{r}
ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_data(samdf), 
               tax_table(taxa))
ps <- prune_samples(sample_names(ps) != "Mock", ps) # Remove mock sample
```
```{r}
dna <- Biostrings::DNAStringSet(taxa_names(ps))
names(dna) <- taxa_names(ps)
ps <- merge_phyloseq(ps, dna)
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps)))
ps
```
#Visualize alpha-diversity:
```{r}
plot_richness(ps, x="Day", measures=c("Shannon", "Simpson"), color="When")
```
#Ordinate:
```{r}
# Transform data to proportions as appropriate for Bray-Curtis distances
ps.prop <- transform_sample_counts(ps, function(otu) otu/sum(otu))
ord.nmds.bray <- ordinate(ps.prop, method="NMDS", distance="bray")
```
```{r}
plot_ordination(ps.prop, ord.nmds.bray, color="When", title="Bray NMDS")
```
#Bar plot:
```{r}
top20 <- names(sort(taxa_sums(ps), decreasing=TRUE))[1:20]
ps.top20 <- transform_sample_counts(ps, function(OTU) OTU/sum(OTU))
ps.top20 <- prune_taxa(top20, ps.top20)
plot_bar(ps.top20, x="Day", fill="Family") + facet_wrap(~When, scales="free_x")
```








